### ISSUE TITLE
Unable to sync and publish repo to github

### ISSUE THREAD

**Issue by sindhus-in** [wixplosives/codux-core#1025]
I have given permissions via oauth to codux app to publish to my github but when I click on "Sync publish project", I see this in the browser:

<img width="398" alt="image" src="https://github.com/wixplosives/codux-core/assets/85542169/961a5e23-db32-4191-a987-3d0fc26c9b9c">

**Comment by tomrav** [comment]
Thank you for reaching out, is it possible you're using Firefox or Safari as your default browser? We've recently encountered some issues around it and are investigating further.

Could you perhaps try using a different browser for logging in?

**Comment by tomrav** [comment]
I'm happy to report that this issue has been resolved, and logging in to GitHub through Codux should now work as expected in all browsers.
