### ISSUE TITLE
CMD+W quits the application

### ISSUE THREAD

**Issue by mnapthine** [wixplosives/codux-core#1055]
Hi all, 

This was unexpected as I was in the Editor view and I expected it to close the file but the application quit instead. This was counterintuitive for me given the vast majority of apps would just close the file or tab etc.

v15.21.0

**Comment by tomrav** [comment]
Hey @mnapthine good to see you around here and thanks for reporting the issue.

This is definitely buggy behavior (happening only when focused on the code drawer), we'll take a look to see how we can sort it out on our end. :)

**Comment by tomrav** [comment]
I'm very happy to say that this issue was fixed in the latest version of Codux - you can find available at the [Codux site](https://codux.com/download).
