### ISSUE TITLE
Codux wide plugins?

### ISSUE THREAD

**Issue by robigan** [wixplosives/codux-core#769]
Will we ever see Codux wide plugins? After having watched the video by Fireship my mind immediately screamed Tailwind integrated dev environment, it would be nice to have a Codux-wide plugin that would allow me to use Tailwind. Honestly such a cool project.

**Comment by tomrav** [comment]
You're already in luck, we just added Tailwind support in our latest version - you can see how to hook it up here: https://help.codux.com/kb/en/article/using-tailwind-css-with-codux
For now, it mostly enables rendering components that use Tailwind, and we have improvements planned for the editing experience in the near future.

As for extensions, it's definitely within our intent - but we need to feel a bit more stable about how Codux behaves, and its value before we open it up to external contributions. But stay tuned, it's definitely in the cards!

**Comment by robigan** [comment]
That's great! I'll be waiting for the editor improvements. Is there a timeframe on that?

**Comment by tomrav** [comment]
No exact timeframe to share, but I hope you'll start seeing these improvements in the coming weeks.
