### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by AbraaoAlves** [wixplosives/codux-core#770]
Is there any support to run codux accessing file from [wsl](https://learn.microsoft.com/pt-br/windows/wsl/)?

**Comment by tomrav** [comment]
Have you tried using our `appImage` download flavor? some users have reported success using it with WSL. Would love to know if solves the issue for you as well.

**Comment by ryanlaufsen** [comment]
Can confirm that `Codux-15.10.0.x86_64.AppImage` works on Ubuntu 22.04.2 in WSL.

**Comment by tomrav** [comment]
Closing as this does in fact seem to be solved.
