### ISSUE TITLE
Download for Mac Intel repeatedly fails with a network issue?

### ISSUE THREAD

**Issue by jeffreybarron** [wixplosives/codux-core#772]
https://www.codux.com/download
https://www.codux.com/_files/archives/e855c7_ee2eb78e05b043a8a6fdbeac60a4e1f5.zip

I would love to try this, I saw it demonstrated on fireship

fails to download on both firefox and chrome. no I dont have problems downloading anything else.

**Comment by tomrav** [comment]
We've replaced our hosting provider, and this issue is now resolved.
