### ISSUE TITLE
dropdown of enum unusable with many options

### ISSUE THREAD

**Issue by auipga** [wixplosives/codux-core#975]
I clicked on the `icon` property to select a different Fontawesome icon. There are a lot.

The dropdown menu repositions to the left and I can not scroll the list so the selection is limited.

![image](https://github.com/wixplosives/codux-core/assets/876689/a89b94d4-c5d9-417b-89da-0d54f93ddcb4)

A search as the first item within the dropdown would be excellent.

I guess this is not OS dependent but anyways I'm running Archlinux and I tried the .pacman file and the AppImage.

**Comment by auipga** [comment]
adding ` | string` ...
```ts
export interface FaIconProps {
  icon: IconName | string;
  fw?: boolean;
}
```
...makes the dropdown disappear leaving me with a plain string input field (which is right I guess, though a suggestion here would be awesome)

**Comment by tomrav** [comment]
Nice workaround you found, but this is definitely an issue we intend on fixing - will update once there's news.

**Comment by 0xRezaa** [comment]
@auipga Thanks for waiting. We fixed this Issue and also [that](https://github.com/wixplosives/codux-core/issues/976) one.

Feel free to check it out yourself. 
Cheers
