### ISSUE TITLE
enum order gets changed on selection

### ISSUE THREAD

**Issue by auipga** [wixplosives/codux-core#976]
```ts
export interface Something {
  just_a_number?: 1|2|3|4|5;
}
```
when selecting a value it gets moved to the top
![image](https://github.com/wixplosives/codux-core/assets/876689/cc463fcd-9e6c-4767-b88a-7f1e72fd55e8)

getting worse when changing again
![image](https://github.com/wixplosives/codux-core/assets/876689/855724b5-793a-4589-a3d4-68379312937b)

**Comment by tomrav** [comment]
This is really weird behavior, we'll into the reason and work on a fix.

**Comment by 0xRezaa** [comment]
This is fixed now. As well as the [other](https://github.com/wixplosives/codux-core/issues/975) issue you opened.
cheers
