### ISSUE TITLE
'view problem' popover stays open after being fixed

### ISSUE THREAD

**Issue by auipga** [wixplosives/codux-core#977]
![image](https://github.com/wixplosives/codux-core/assets/876689/d9601e9d-8697-4bef-b2dd-de918c1255e2)

I can even click or type in de code editor without it getting closed.
Clicking on the 'x' works as intended. Folding the code section with the former error also closes it.

To be fair: I fixed my error (a missing import) from outside.

**Comment by tomrav** [comment]
This actually seems somewhat identical to how VSCode behaves as well, opening the "problem panel" is a somewhat fixed action, hitting the esc key also closes it. 

Closing this issue as working as expected, if you intended for something else to happen please feel free to write back/reopen.
