### ISSUE TITLE
'Edit Code' button selects not all relevant code

### ISSUE THREAD

**Issue by auipga** [wixplosives/codux-core#978]
Cases:

1. has no child `<br/>`
2. has child `<br/>`, correct behaviour
3. has child `<br/>`, **incorrect** behaviour

Somtimes only the inner `<br/>` gets selected. I can't identify a pattern.

1: always correct
![image](https://github.com/wixplosives/codux-core/assets/876689/72d35809-0b0f-4390-a520-8e2b9a5f42a0)

2: this time correct
![image](https://github.com/wixplosives/codux-core/assets/876689/ee7f7f5a-5a03-4d52-9eb3-d55e933369fa)

3: but most of the time incorrect
![image](https://github.com/wixplosives/codux-core/assets/876689/ed587d1f-1c21-43f9-8fd5-dfdcc97e8a48)

**Comment by tomrav** [comment]
This issue has been resolved in the latest version of Codux.
Please let us know if you're encountering any further issues.
