### ISSUE TITLE
Error when launching Codux on Windows: TypeError: fetch failed

### ISSUE THREAD

**Issue by OlegAlexanderLowes** [wixplosives/codux-core#980]
Hello and thank you for creating Codux!

I want to report an error when launching Codux on Windows.

![codux_error](https://github.com/wixplosives/codux-core/assets/60194926/f922a09c-5b92-4681-8773-020205258bc2)

```
TypeError: fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11413:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Upon deeper investigation, the error has to do with failing to remove the following directory: `C:\Users\USER\AppData\Local\Temp\codux-1701979052902`. The numbers at the end are different every time I tried to launch Codux, but it seems that Codux creates this directory and then tries to immediately delete it.

My environment: Windows 11 Enterprise 64bit, Node v21.4.0

At first I tried downgrading my node version, but that didn't work.

The actual workaround is to install Codux version 15.8.0, which launches normally. I determined this by doing a binary search on the [installation files](https://github.com/wixplosives/codux-versions) to see if an earlier version worked. Version 15.9.0 and above have the error.

Thank you.

**Comment by tomrav** [comment]
Thank you for reporting this issue, we've started investigating and will report back here once we have a lead.

**Comment by tomrav** [comment]
We believe we have identified and resolved the issue, you should be able to open Codux on any of the latest versions without any crashes happening. We'd love to hear back if everything is working as expected.

**Comment by OlegAlexanderLowes** [comment]
Indeed! Version 15.16.1 is working for me. Thanks for the quick turnaround!
